### ISSUE TITLE
Link back to my site?

### ISSUE THREAD

**Issue by beingretrogamer** [doqmeat/doqmeat.com#34]
Hi Des, I found your website super interesting and innovative and I think love for gaming is common b/w us. Do you mind linking to my retro gaming website here - https://theretrosaga.com/
There are tons of retro games for you to play here. Please give it a try and also send some feedback if you can.

Thanks a ton!

**Comment by beingretrogamer** [comment]
Also, I will be more than happy to link back to yours :)

**Comment by doqmeat** [comment]
i'm not exactly interested but thank you for the nice message :)

**Comment by beingretrogamer** [comment]
No stress at all Des! Thanks for replying so quickly. Do you know if any
one else in your network can do link exchange? I am really struggling to
get traffic and would appreciate your help.
